### ISSUE TITLE
Add comunication parts & protocols

### ISSUE THREAD

**Issue by MattZK** [AP-Elektronica-ICT/jp19-lafa#4]
- ESPx
- TCP/IP
- I2C
etc.

**Comment by F0xedb** [comment]
Added basic communication markdown. Concrete information about the parts list must be added (a few examples are listed but not complete) This is because I don't know the seller of our school. After I know this information I can pick concrete parts. Also for the network side of things I picked switches (should these be HUB's or can we spare that little bit extra money?)
